Kate/home/grig
Ezhukovich1/BA_FE_125_Course pull request #237
Opened 2023-10-20 09:21 UTC by KateAkulenko

Hello check my homework about grids
![image](https://github.com/Ezhukovich1/BA_FE_125_Course/assets/144695048/486aba74-5ab5-4bc3-9f72-570361ba0fb3)

2023-10-25 14:50 UTC, Ezhukovich1 commented
Як так вийшло що в тебе в домашці з грідами є, домашка з формами?
Ти після того як зробила домашнє, ти переключаєшся на гілку **main** а потім з ней створюєш нову гілку?

2023-10-25 14:53 UTC, Ezhukovich1 commented on Akulenko/homework/grid/img/blure.svg
Я думаю що цей блюр ти могла б накласти через background, а потім виставити його в середені елемента через позиціонування. Або зразу експортувати картинку з цим блюром

2023-10-25 14:58 UTC, Ezhukovich1 requested changes
Продивись мої коментарі, та дай на них відповідь.
В цілому по роботі питань немає, дякую!

2023-10-25 17:17 UTC, KateAkulenko commented on Akulenko/homework/grid/img/blure.svg
Ні я не переключалась тоді на мейн а просто створила наступну гілку.
Ну я не накладала блюр а прописала фільтр в CSS однією строчкою.

2023-10-26 06:58 UTC, Ezhukovich1 commented on Akulenko/homework/grid/img/blure.svg
Саме тому прошу, будь ласка ЗАВЖДИ, перед тим як створювати нову гілку, спочатку переключись на **main**, а потім вже створюю нову гілку.
Це дуже важливо в перспективі на майбутнє, це має бути як звичка.

2023-10-26 06:58 UTC, Ezhukovich1 approved these changes

2023-10-26 16:36 UTC, KateAkulenko commented
Дякую мерджу

2023-10-26 16:36 UTC, merged